// Generated by CoffeeScript 1.10.0
(function() {
  var Stomp, fs;

  Stomp = require('../lib/stomp-node.js');

  fs = require('fs');

  describe("Stomp Node", function() {
    it("lets you connect to a server with TCP socket and get a callback", function(done) {
      var client, connectionHeaders;
      client = Stomp.overTCP('localhost', 61613);
      connectionHeaders = {
        'max_hbrlck_fails': 10,
        'accept-version': '1.0,1.1,1.2',
        'heart-beat': '10000,10000',
        login: 'c39b1999-2786-44e1-a76c-7a5cd6e18b73',
        passcode: 'Rbqw8X-yzM-iVkEWSzsAwXvtRXUw5qz_5U_JVsst',
        host: '34a76890-9b71-4dfb-8baa-c1f394489c95'
      };
      return client.connect(connectionHeaders, function() {
        expect(client.connected).toBe(true);
        client.disconnect();
        return done();
      });
    });
    return it("lets you connect to a server with SSL TCP socket and get a callback", function(done) {
      var client, connectionHeaders, sslOptions;
      sslOptions = {
        cert: fs.readFileSync('/Users/gfoiani/tls-gen/basic/result/client_certificate.pem'),
        key: fs.readFileSync('/Users/gfoiani/tls-gen/basic/result/client_key.pem'),
        ca: [fs.readFileSync('/Users/gfoiani/tls-gen/basic/result/ca_certificate.pem')],
        secureProtocol: 'TLSv1_method'
      };
      client = Stomp.overTCP('FojaMac', 61614, sslOptions);
      connectionHeaders = {
        'max_hbrlck_fails': 10,
        'accept-version': '1.0,1.1,1.2',
        'heart-beat': '10000,10000',
        login: 'c39b1999-2786-44e1-a76c-7a5cd6e18b73',
        passcode: 'Rbqw8X-yzM-iVkEWSzsAwXvtRXUw5qz_5U_JVsst',
        host: '34a76890-9b71-4dfb-8baa-c1f394489c95'
      };
      return client.connect(connectionHeaders, (function() {
        expect(client.connected).toBe(true);
        client.disconnect();
        return done();
      }), function(err) {
        console.log(err);
        return done.fail('connection SSL error');
      });
    });
  });

}).call(this);
