// Generated by CoffeeScript 1.10.0
(function() {
  var Stomp, StompServerMock;

  Stomp = require('../lib/stomp.js').Stomp;

  StompServerMock = require('./server.mock.js').StompServerMock;

  Stomp.WebSocketClass = StompServerMock;

  describe("Stomp", function() {
    it("lets you connect to a server with a websocket and get a callback", function(done) {
      var client, connected, ws;
      ws = new StompServerMock("ws://mocked/stomp/server");
      client = Stomp.over(ws);
      connected = false;
      return client.connect("guest", "guest", function() {
        connected = true;
        expect(client.connected).toBe(true);
        return done();
      });
    });
    it("lets you connect to a server and get a callback", function(done) {
      var client, connected;
      client = Stomp.client("ws://mocked/stomp/server");
      connected = false;
      return client.connect("guest", "guest", function() {
        connected = true;
        expect(client.connected).toBe(true);
        return done();
      });
    });
    it("lets you subscribe to a destination", function(done) {
      var client, subscription;
      client = Stomp.client("ws://mocked/stomp/server");
      subscription = null;
      return client.connect("guest", "guest", function() {
        subscription = client.subscribe("/queue/test");
        expect(Object.keys(client.ws.subscriptions)).toContain(subscription.id);
        return done();
      });
    });
    it("lets you publish a message to a destination", function(done) {
      var client, message;
      client = Stomp.client("ws://mocked/stomp/server");
      message = null;
      return client.connect("guest", "guest", function() {
        message = "Hello world!";
        client.send("/queue/test", {}, message);
        expect(client.ws.messages.pop().toString()).toContain(message);
        return done();
      });
    });
    it("lets you unsubscribe from a destination", function(done) {
      var client, subscription, unsubscribed;
      client = Stomp.client("ws://mocked/stomp/server");
      unsubscribed = false;
      subscription = null;
      return client.connect("guest", "guest", function() {
        subscription = client.subscribe("/queue/test");
        subscription.unsubscribe();
        unsubscribed = true;
        expect(Object.keys(client.ws.subscriptions)).not.toContain(subscription.id);
        return done();
      });
    });
    it("lets you receive messages only while subscribed", function(done) {
      var client, messages, subscription;
      client = Stomp.client("ws://mocked/stomp/server");
      subscription = null;
      messages = [];
      return client.connect("guest", "guest", function() {
        var err, error;
        subscription = client.subscribe("/queue/test", function(msg) {
          return messages.push(msg);
        });
        client.ws.test_send(subscription.id, Math.random());
        client.ws.test_send(subscription.id, Math.random());
        expect(messages.length).toEqual(2);
        subscription.unsubscribe();
        try {
          client.ws.test_send(id, Math.random());
        } catch (error) {
          err = error;
          null;
        }
        expect(messages.length).toEqual(2);
        return done();
      });
    });
    it("lets you send messages in a transaction", function(done) {
      var client, connected;
      client = Stomp.client("ws://mocked/stomp/server");
      connected = false;
      return client.connect("guest", "guest", function() {
        var txid;
        connected = true;
        txid = "123";
        client.begin(txid);
        client.send("/queue/test", {
          transaction: txid
        }, "messages 1");
        client.send("/queue/test", {
          transaction: txid
        }, "messages 2");
        expect(client.ws.messages.length).toEqual(0);
        client.send("/queue/test", {
          transaction: txid
        }, "messages 3");
        client.commit(txid);
        expect(client.ws.messages.length).toEqual(3);
        return done();
      });
    });
    return it("lets you abort a transaction", function(done) {
      var client, connected;
      client = Stomp.client("ws://mocked/stomp/server");
      connected = false;
      return client.connect("guest", "guest", function() {
        var txid;
        connected = true;
        txid = "123";
        client.begin(txid);
        client.send("/queue/test", {
          transaction: txid
        }, "messages 1");
        client.send("/queue/test", {
          transaction: txid
        }, "messages 2");
        expect(client.ws.messages.length).toEqual(0);
        client.send("/queue/test", {
          transaction: txid
        }, "messages 3");
        client.abort(txid);
        expect(client.ws.messages.length).toEqual(0);
        return done();
      });
    });
  });

}).call(this);
